server:
  port: 9002
eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}/actuator/info
    lease-renewal-interval-in-seconds: 30 # 测试心跳时间间隔
    lease-expiration-duration-in-seconds: 300 # 服务时效时间
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: client2
info:
  app:
    name: client2
    version: v1.0.0
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
